import { sendTemplateEmail } from "@/lib/brevo/sendTemplateEmail";
import { eodExcelFilename } from "@/lib/eod/exportEodExcel";
import { eodPdfFilename } from "@/lib/eod/exportEodPdf";

const money = (n) =>
  `$${(Math.round((Number(n) || 0) * 100) / 100).toFixed(2)}`;

/**
 * Email End-of-Day PDF + Excel via existing Brevo infrastructure.
 */
export async function sendEodReportEmail({
  to,
  report,
  pdfBuffer,
  excelBuffer,
}) {
  const businessDate = report.meta?.businessDate || "";
  const restaurantName = report.meta?.restaurantName || "Tasty Bites";
  const summary = report.summary || {};
  const subject = `${restaurantName} — End of Day Report — ${businessDate}`;

  const generatedBy =
    report.meta?.generatedByName || report.cashDeposit?.createdBy || "—";
  const generatedAt = report.meta?.generatedAt
    ? new Date(report.meta.generatedAt).toLocaleString()
    : "—";

  const htmlContent = `
    <div style="font-family: Arial, sans-serif; color: #222; line-height: 1.5;">
      <h2 style="margin-bottom: 8px;">${restaurantName} — End of Day Report</h2>
      <p style="margin: 0 0 16px;">Please find the End-of-Day report attached (PDF and Excel).</p>
      <table style="border-collapse: collapse; min-width: 320px;">
        <tr><td style="padding: 4px 12px 4px 0;"><strong>Business Day</strong></td><td>${businessDate}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0;"><strong>Net Sales</strong></td><td>${money(summary.netSales)}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0;"><strong>Total Payments</strong></td><td>${money(summary.totalPayment)}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0;"><strong>Total Taxes</strong></td><td>${money(summary.taxes)}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0;"><strong>Total Tips</strong></td><td>${money(summary.tips)}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0;"><strong>Total Refunds</strong></td><td>${money(summary.refunds)}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0;"><strong>Generated By</strong></td><td>${generatedBy}</td></tr>
        <tr><td style="padding: 4px 12px 4px 0;"><strong>Generated At</strong></td><td>${generatedAt}</td></tr>
      </table>
      <p style="margin-top: 16px; color: #666; font-size: 12px;">Attachments: ${eodPdfFilename(businessDate)}, ${eodExcelFilename(businessDate)}</p>
    </div>
  `;

  const attachment = [
    {
      name: eodPdfFilename(businessDate),
      content: Buffer.from(pdfBuffer).toString("base64"),
    },
    {
      name: eodExcelFilename(businessDate),
      content: Buffer.from(excelBuffer).toString("base64"),
    },
  ];

  return sendTemplateEmail({
    to: [{ email: to }],
    subject,
    htmlContent,
    attachment,
  });
}
